name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Test
      uses: ./
      run: docker build -t sim/react-test -f ./client/Dockerfile.dev .
      run: docker run -e CI=true sim/react-test npm test -- -- coverage

    - name: Build the Docker images
      uses: ./
      run: docker build -t sim/multi-client ./client
      run: docker build -t sim/multi-nginx ./nginx
      run: docker build -t sim/multi-server ./server
      run: docker build -t sim/multi-worker ./worker
