name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ozcnsimge/react-test -f ./client/Dockerfile.dev ./client
    - name: Run frontend tests
      run: docker run -e CI=true ozcnsimge/react-test npm test
    - name: Build production images
      run: |
        docker build -t ozcnsimge/multi-client ./client
        docker build -t ozcnsimge/multi-nginx ./nginx
        docker build -t ozcnsimge/multi-server ./server
        docker build -t ozcnsimge/multi-worker ./worker
    - name: Login docker CLI
      env:
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    - name: Push images to docker hub
      run: |
        docker push ozcnsimge/multi-client
        docker push ozcnsimge/multi-nginx
        docker push ozcnsimge/multi-server
        docker push ozcnsimge/multi-worker
