name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t sim/react-test -f ./client/Dockerfile.dev ./client
    - name: Run frontend tests
      run: docker run -e CI=true sim/react-test npm test
    - name: Run frontend tests
      run: |
        docker build -t sim/multi-client ./client
        docker build -t sim/multi-nginx ./nginx
        docker build -t sim/multi-server ./server
        docker build -t sim/multi-worker ./worker
